/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.visualbuilder.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.visualbuilder.struts.beans.User;

/*
 * @author VisualBuilder
 */

public class LoginAction extends Action {

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		User userForm = (User)form;
		String user = userForm.getUserId();
		String password = userForm.getPassword();
		if(user.equals("admin") && password.equals("admin"))
			return mapping.findForward("success");
		ActionMessages errors = new ActionMessages();
		ActionMessage error = new ActionMessage("login.failed");
		errors.add("error",error);
		saveErrors(request, errors);
		return mapping.findForward("failure");
	}
}