/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.visualbuilder.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.visualbuilder.struts.db.UserManager;

/*
 * @author VisualBuilder
 */

public class ManageUsersAction extends Action {

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//Get a list of users and save to the request
		try{
			List list = UserManager.getInstance().list();
			request.setAttribute("list", list);
		}catch(SQLException sqle)
		{
			ActionMessages errors = new ActionMessages();
			ActionMessage error = new ActionMessage("error.generic",sqle.getMessage());
			errors.add("error",error);
			saveErrors(request, errors);
		}
		return mapping.findForward("success");
	}
}